name: Install seo-optimizer
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NUMBER_OF_ITERATIONS: 30
    steps:
      - name: Install & Uninstall seo-optimizer
        run: |
          for i in $(seq 1 $NUMBER_OF_ITERATIONS)
          do
            MINWAIT=1
            MAXWAIT=5
            sleep $((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
            npm install -g --no-cache seo-optimizer
            npm uninstall -g seo-optimizer
          done
